// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TimeZoneServiceClient is the client API for TimeZoneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TimeZoneServiceClient interface {
	TimeZoneDetails(ctx context.Context, in *TimeZoneRequest, opts ...grpc.CallOption) (*TimeZoneResponse, error)
}

type timeZoneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTimeZoneServiceClient(cc grpc.ClientConnInterface) TimeZoneServiceClient {
	return &timeZoneServiceClient{cc}
}

func (c *timeZoneServiceClient) TimeZoneDetails(ctx context.Context, in *TimeZoneRequest, opts ...grpc.CallOption) (*TimeZoneResponse, error) {
	out := new(TimeZoneResponse)
	err := c.cc.Invoke(ctx, "/TimeZoneService/TimeZoneDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimeZoneServiceServer is the server API for TimeZoneService service.
// All implementations must embed UnimplementedTimeZoneServiceServer
// for forward compatibility
type TimeZoneServiceServer interface {
	TimeZoneDetails(context.Context, *TimeZoneRequest) (*TimeZoneResponse, error)
	mustEmbedUnimplementedTimeZoneServiceServer()
}

// UnimplementedTimeZoneServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTimeZoneServiceServer struct {
}

func (UnimplementedTimeZoneServiceServer) TimeZoneDetails(context.Context, *TimeZoneRequest) (*TimeZoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TimeZoneDetails not implemented")
}
func (UnimplementedTimeZoneServiceServer) mustEmbedUnimplementedTimeZoneServiceServer() {}

// UnsafeTimeZoneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TimeZoneServiceServer will
// result in compilation errors.
type UnsafeTimeZoneServiceServer interface {
	mustEmbedUnimplementedTimeZoneServiceServer()
}

func RegisterTimeZoneServiceServer(s grpc.ServiceRegistrar, srv TimeZoneServiceServer) {
	s.RegisterService(&TimeZoneService_ServiceDesc, srv)
}

func _TimeZoneService_TimeZoneDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeZoneServiceServer).TimeZoneDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TimeZoneService/TimeZoneDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeZoneServiceServer).TimeZoneDetails(ctx, req.(*TimeZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TimeZoneService_ServiceDesc is the grpc.ServiceDesc for TimeZoneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TimeZoneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TimeZoneService",
	HandlerType: (*TimeZoneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TimeZoneDetails",
			Handler:    _TimeZoneService_TimeZoneDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
